/*
 * This file is generated by jOOQ.
 */
package ru.tinkoff.edu.java.scrapper.service.impl.jooq.codegen.public_.tables;


import java.util.Arrays;
import java.util.List;
import java.util.function.Function;

import javax.annotation.processing.Generated;

import org.jetbrains.annotations.NotNull;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function2;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row2;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import ru.tinkoff.edu.java.scrapper.service.impl.jooq.codegen.public_.Keys;
import ru.tinkoff.edu.java.scrapper.service.impl.jooq.codegen.public_.Public;
import ru.tinkoff.edu.java.scrapper.service.impl.jooq.codegen.public_.tables.records.SoAnswerCountRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.17.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SoAnswerCount extends TableImpl<SoAnswerCountRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.so_answer_count</code>
     */
    public static final SoAnswerCount SO_ANSWER_COUNT = new SoAnswerCount();

    /**
     * The class holding records for this type
     */
    @Override
    @NotNull
    public Class<SoAnswerCountRecord> getRecordType() {
        return SoAnswerCountRecord.class;
    }

    /**
     * The column <code>public.so_answer_count.link_id</code>.
     */
    public final TableField<SoAnswerCountRecord, Long> LINK_ID = createField(DSL.name("link_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.so_answer_count.count</code>.
     */
    public final TableField<SoAnswerCountRecord, Long> COUNT = createField(DSL.name("count"), SQLDataType.BIGINT.nullable(false), this, "");

    private SoAnswerCount(Name alias, Table<SoAnswerCountRecord> aliased) {
        this(alias, aliased, null);
    }

    private SoAnswerCount(Name alias, Table<SoAnswerCountRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.so_answer_count</code> table reference
     */
    public SoAnswerCount(String alias) {
        this(DSL.name(alias), SO_ANSWER_COUNT);
    }

    /**
     * Create an aliased <code>public.so_answer_count</code> table reference
     */
    public SoAnswerCount(Name alias) {
        this(alias, SO_ANSWER_COUNT);
    }

    /**
     * Create a <code>public.so_answer_count</code> table reference
     */
    public SoAnswerCount() {
        this(DSL.name("so_answer_count"), null);
    }

    public <O extends Record> SoAnswerCount(Table<O> child, ForeignKey<O, SoAnswerCountRecord> key) {
        super(child, key, SO_ANSWER_COUNT);
    }

    @Override
    @NotNull
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    @NotNull
    public UniqueKey<SoAnswerCountRecord> getPrimaryKey() {
        return Keys.SO_ANSWER_COUNT_PKEY;
    }

    @Override
    @NotNull
    public List<ForeignKey<SoAnswerCountRecord, ?>> getReferences() {
        return Arrays.asList(Keys.SO_ANSWER_COUNT__SO_ANSWER_COUNT_LINK_ID_FKEY);
    }

    private transient Link _link;

    /**
     * Get the implicit join path to the <code>public.link</code> table.
     */
    public Link link() {
        if (_link == null)
            _link = new Link(this, Keys.SO_ANSWER_COUNT__SO_ANSWER_COUNT_LINK_ID_FKEY);

        return _link;
    }

    @Override
    @NotNull
    public SoAnswerCount as(String alias) {
        return new SoAnswerCount(DSL.name(alias), this);
    }

    @Override
    @NotNull
    public SoAnswerCount as(Name alias) {
        return new SoAnswerCount(alias, this);
    }

    @Override
    @NotNull
    public SoAnswerCount as(Table<?> alias) {
        return new SoAnswerCount(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    @NotNull
    public SoAnswerCount rename(String name) {
        return new SoAnswerCount(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    @NotNull
    public SoAnswerCount rename(Name name) {
        return new SoAnswerCount(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    @NotNull
    public SoAnswerCount rename(Table<?> name) {
        return new SoAnswerCount(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row2 type methods
    // -------------------------------------------------------------------------

    @Override
    @NotNull
    public Row2<Long, Long> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function2<? super Long, ? super Long, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function2<? super Long, ? super Long, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
