/*
 * This file is generated by jOOQ.
 */
package ru.tinkoff.edu.java.scrapper.service.impl.jooq.codegen.public_.tables.records;


import java.beans.ConstructorProperties;

import javax.annotation.processing.Generated;

import org.jetbrains.annotations.NotNull;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;

import ru.tinkoff.edu.java.scrapper.service.impl.jooq.codegen.public_.tables.SoAnswerCount;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.17.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SoAnswerCountRecord extends UpdatableRecordImpl<SoAnswerCountRecord> implements Record2<Long, Long> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.so_answer_count.link_id</code>.
     */
    public void setLinkId(@NotNull Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.so_answer_count.link_id</code>.
     */
    @jakarta.validation.constraints.NotNull
    @NotNull
    public Long getLinkId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.so_answer_count.count</code>.
     */
    public void setCount(@NotNull Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.so_answer_count.count</code>.
     */
    @jakarta.validation.constraints.NotNull
    @NotNull
    public Long getCount() {
        return (Long) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    @NotNull
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    @NotNull
    public Row2<Long, Long> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    @NotNull
    public Row2<Long, Long> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    @NotNull
    public Field<Long> field1() {
        return SoAnswerCount.SO_ANSWER_COUNT.LINK_ID;
    }

    @Override
    @NotNull
    public Field<Long> field2() {
        return SoAnswerCount.SO_ANSWER_COUNT.COUNT;
    }

    @Override
    @NotNull
    public Long component1() {
        return getLinkId();
    }

    @Override
    @NotNull
    public Long component2() {
        return getCount();
    }

    @Override
    @NotNull
    public Long value1() {
        return getLinkId();
    }

    @Override
    @NotNull
    public Long value2() {
        return getCount();
    }

    @Override
    @NotNull
    public SoAnswerCountRecord value1(@NotNull Long value) {
        setLinkId(value);
        return this;
    }

    @Override
    @NotNull
    public SoAnswerCountRecord value2(@NotNull Long value) {
        setCount(value);
        return this;
    }

    @Override
    @NotNull
    public SoAnswerCountRecord values(@NotNull Long value1, @NotNull Long value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SoAnswerCountRecord
     */
    public SoAnswerCountRecord() {
        super(SoAnswerCount.SO_ANSWER_COUNT);
    }

    /**
     * Create a detached, initialised SoAnswerCountRecord
     */
    @ConstructorProperties({ "linkId", "count" })
    public SoAnswerCountRecord(@NotNull Long linkId, @NotNull Long count) {
        super(SoAnswerCount.SO_ANSWER_COUNT);

        setLinkId(linkId);
        setCount(count);
    }

    /**
     * Create a detached, initialised SoAnswerCountRecord
     */
    public SoAnswerCountRecord(ru.tinkoff.edu.java.scrapper.service.impl.jooq.codegen.public_.tables.pojos.SoAnswerCount value) {
        super(SoAnswerCount.SO_ANSWER_COUNT);

        if (value != null) {
            setLinkId(value.getLinkId());
            setCount(value.getCount());
        }
    }
}
