/*
 * This file is generated by jOOQ.
 */
package ru.tinkoff.edu.java.scrapper.service.impl.jooq.codegen.public_;


import javax.annotation.processing.Generated;

import org.jooq.ForeignKey;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;

import ru.tinkoff.edu.java.scrapper.service.impl.jooq.codegen.public_.tables.Chat;
import ru.tinkoff.edu.java.scrapper.service.impl.jooq.codegen.public_.tables.ChatLink;
import ru.tinkoff.edu.java.scrapper.service.impl.jooq.codegen.public_.tables.Databasechangeloglock;
import ru.tinkoff.edu.java.scrapper.service.impl.jooq.codegen.public_.tables.GithubRepositoryIssue;
import ru.tinkoff.edu.java.scrapper.service.impl.jooq.codegen.public_.tables.Link;
import ru.tinkoff.edu.java.scrapper.service.impl.jooq.codegen.public_.tables.SoAnswerCount;
import ru.tinkoff.edu.java.scrapper.service.impl.jooq.codegen.public_.tables.records.ChatLinkRecord;
import ru.tinkoff.edu.java.scrapper.service.impl.jooq.codegen.public_.tables.records.ChatRecord;
import ru.tinkoff.edu.java.scrapper.service.impl.jooq.codegen.public_.tables.records.DatabasechangeloglockRecord;
import ru.tinkoff.edu.java.scrapper.service.impl.jooq.codegen.public_.tables.records.GithubRepositoryIssueRecord;
import ru.tinkoff.edu.java.scrapper.service.impl.jooq.codegen.public_.tables.records.LinkRecord;
import ru.tinkoff.edu.java.scrapper.service.impl.jooq.codegen.public_.tables.records.SoAnswerCountRecord;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * public.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.17.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<ChatRecord> CHAT_PKEY = Internal.createUniqueKey(Chat.CHAT, DSL.name("chat_pkey"), new TableField[] { Chat.CHAT.ID }, true);
    public static final UniqueKey<ChatLinkRecord> CHAT_LINK_PKEY = Internal.createUniqueKey(ChatLink.CHAT_LINK, DSL.name("chat_link_pkey"), new TableField[] { ChatLink.CHAT_LINK.CHAT_ID, ChatLink.CHAT_LINK.LINK_ID }, true);
    public static final UniqueKey<DatabasechangeloglockRecord> DATABASECHANGELOGLOCK_PKEY = Internal.createUniqueKey(Databasechangeloglock.DATABASECHANGELOGLOCK, DSL.name("databasechangeloglock_pkey"), new TableField[] { Databasechangeloglock.DATABASECHANGELOGLOCK.ID }, true);
    public static final UniqueKey<GithubRepositoryIssueRecord> GITHUB_REPOSITORY_ISSUE_PKEY = Internal.createUniqueKey(GithubRepositoryIssue.GITHUB_REPOSITORY_ISSUE, DSL.name("github_repository_issue_pkey"), new TableField[] { GithubRepositoryIssue.GITHUB_REPOSITORY_ISSUE.ID }, true);
    public static final UniqueKey<GithubRepositoryIssueRecord> UQ_GITHUB_REPOSITORY_ISSUE = Internal.createUniqueKey(GithubRepositoryIssue.GITHUB_REPOSITORY_ISSUE, DSL.name("uq_github_repository_issue"), new TableField[] { GithubRepositoryIssue.GITHUB_REPOSITORY_ISSUE.ID, GithubRepositoryIssue.GITHUB_REPOSITORY_ISSUE.LINK_ID }, true);
    public static final UniqueKey<LinkRecord> LINK_PKEY = Internal.createUniqueKey(Link.LINK, DSL.name("link_pkey"), new TableField[] { Link.LINK.ID }, true);
    public static final UniqueKey<LinkRecord> LINK_URL_KEY = Internal.createUniqueKey(Link.LINK, DSL.name("link_url_key"), new TableField[] { Link.LINK.URL }, true);
    public static final UniqueKey<SoAnswerCountRecord> SO_ANSWER_COUNT_PKEY = Internal.createUniqueKey(SoAnswerCount.SO_ANSWER_COUNT, DSL.name("so_answer_count_pkey"), new TableField[] { SoAnswerCount.SO_ANSWER_COUNT.LINK_ID }, true);

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<ChatLinkRecord, ChatRecord> CHAT_LINK__CHAT_LINK_CHAT_ID_FKEY = Internal.createForeignKey(ChatLink.CHAT_LINK, DSL.name("chat_link_chat_id_fkey"), new TableField[] { ChatLink.CHAT_LINK.CHAT_ID }, Keys.CHAT_PKEY, new TableField[] { Chat.CHAT.ID }, true);
    public static final ForeignKey<ChatLinkRecord, LinkRecord> CHAT_LINK__CHAT_LINK_LINK_ID_FKEY = Internal.createForeignKey(ChatLink.CHAT_LINK, DSL.name("chat_link_link_id_fkey"), new TableField[] { ChatLink.CHAT_LINK.LINK_ID }, Keys.LINK_PKEY, new TableField[] { Link.LINK.ID }, true);
    public static final ForeignKey<GithubRepositoryIssueRecord, LinkRecord> GITHUB_REPOSITORY_ISSUE__GITHUB_REPOSITORY_ISSUE_LINK_ID_FKEY = Internal.createForeignKey(GithubRepositoryIssue.GITHUB_REPOSITORY_ISSUE, DSL.name("github_repository_issue_link_id_fkey"), new TableField[] { GithubRepositoryIssue.GITHUB_REPOSITORY_ISSUE.LINK_ID }, Keys.LINK_PKEY, new TableField[] { Link.LINK.ID }, true);
    public static final ForeignKey<SoAnswerCountRecord, LinkRecord> SO_ANSWER_COUNT__SO_ANSWER_COUNT_LINK_ID_FKEY = Internal.createForeignKey(SoAnswerCount.SO_ANSWER_COUNT, DSL.name("so_answer_count_link_id_fkey"), new TableField[] { SoAnswerCount.SO_ANSWER_COUNT.LINK_ID }, Keys.LINK_PKEY, new TableField[] { Link.LINK.ID }, true);
}
